export const REFERENCE_DURABLE_PROBE_CREATE_HANDLER = Symbol(
  "REFERENCE_DURABLE_PROBE_CREATE_HANDLER"
);
export const REFERENCE_DURABLE_PROBE_REPOSITORY = Symbol("REFERENCE_DURABLE_PROBE_REPOSITORY");
export const REFERENCE_DURABLE_PROBE_STATUS_HANDLER = Symbol(
  "REFERENCE_DURABLE_PROBE_STATUS_HANDLER"
);
